language: objective-c
before_script:
    - brew update
    - brew install xctool && brew cleanup xctool
script:
    - cd NitroKeychain
    - xctool -workspace NitroKeychain.xcworkspace -sdk iphonesimulator -scheme NitroKeychain test
