language: objective-c
before_script:
    - brew update
    - brew install xctool && brew cleanup xctool
script:
    - cd NitroKeychain
    - xctool -project NitroKeychain.xcodeproj -sdk iphonesimulator -scheme NitroKeychain test
